name: pi_agenda
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.5.0
  get_it: ^8.0.2

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path:
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  mobx_codegen: ^2.6.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

  injectable_generator:  
  build_runner: ^2.4.13

flutter:

  
  uses-material-design: true

